config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :views

  root 'static_pages#home'

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply, :restore, :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  resources :genres, only: [:show]
  get 'physical_books/searchbook' => 'physical_books#retrieve_from_ggb'
  resources 'physical_books'
  resources 'users', only: [:index, :show]
  get 'users/:id/index_of_books' => 'users#index_of_books', as: :index_of_books


  resource :wishlist, only: [:show]
  resources :wishlist_items, only: [:create, :destroy]

  get "static_pages/about", :as => 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/physical_book.rb
class PhysicalBook < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :transactions
  has_many :wishlist_items

  validates :status, presence: true
  # validates :picture_url, presence: true
  validates :price, presence: true, numericality: true

  # Uploader of pictures
  mount_uploader :picture_url, PhotoUploader

  # advanced search
  searchkick
  after_create { PhysicalBook.reindex }

  def self.text_search(query)
    @results = PhysicalBook.search "#{query}", index_name: [PhysicalBook.search, Genre.search, User.search]
  end

  # googlemaps coordinates
  def user_coordinates
    [user.latitude, user.longitude]
  end
end

app/controllers/physical_books_controller.rb
class PhysicalBooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show] # check if :edit, :update, are needed
  before_filter :require_permission, only: :destroy

  def index
    @physical_books = PhysicalBook.text_search(params[:query])
  end

  def new
    @new_physical_book = PhysicalBook.new
    if params[:title]
      @new_physical_book.title = params[:title]
      @new_physical_book.author = params[:authors]
      @new_physical_book.description = params[:description]
      @new_physical_book.cover_pic_url = params[:cover_pic_url]
      @new_physical_book.isbn = params[:isbn]
    end
  end

  def retrieve_from_ggb
    require 'googlebooks' # unless you're using Bundler
    @searched_books = GoogleBooks.search("#{params[:title_query]}", {:api_key => ENV['BOOKS_API_SERVER_KEY']})
  end

def create
  @new_physical_book = PhysicalBook.new(physical_book_params)
  @new_physical_book.user = current_user
  if @new_physical_book.save
    redirect_to user_path(current_user)
  else
    render :new
  end
end

def show
  @genre = @book.genre
  @hash = Gmaps4rails.build_markers(@book.user) do |user, marker|
    marker.lat user.latitude
    marker.lng user.longitude
    marker.infowindow render_to_string(partial: "static_pages/user_map_box", locals: { user: user})
  end
end

def list

end


def update
  if @book.update(physical_book_params)
    redirect_to root_path
  else
    render :edit
  end
end

def destroy
  @book.destroy
  redirect_to user_path(current_user)
end

private

def physical_book_params
  params.require(:physical_book).permit(:title, :author, :description, :status, :cover_pic_url, :price, :picture_url, :picture_url_cache, :genre_id)
end

def set_book
  @book = PhysicalBook.find(params[:id])
end


def require_permission
  if current_user != PhysicalBook.find(params[:id]).user
    redirect_to root_path
      #Or do something else here
    end
  end

end

app/helpers/physical_books_helper.rb
module PhysicalBooksHelper
  def display_book_price(book)
    if book.price > 0
      "| € #{book.price}"
    else
      ""
    end
  end
end

app/views/physical_books/_google_maps.erb
<div id="map" style="width: 100%; height: 385px;"></div>
        <% content_for(:after_js) do %>
          <script type="text/javascript">
            $(document).on('ready', function() {
              var handler = Gmaps.build('Google');
              var mapOptions = {
                center: new google.maps.LatLng(<%=@book.user.latitude %>,<%=@book.user.longitude %>),
                zoom: 10,
                scrollwheel: false,
                styles: [{"featureType":"landscape","elementType":"all","stylers":[{"hue":"#FFBB00"},{"saturation":43.400000000000006},{"lightness":37.599999999999994},{"gamma":1}]},{"featureType":"poi","elementType":"all","stylers":[{"hue":"#00FF6A"},{"saturation":-1.0989010989011234},{"lightness":11.200000000000017},{"gamma":1}]},{"featureType":"road.highway","elementType":"all","stylers":[{"hue":"#FFC200"},{"saturation":-61.8},{"lightness":45.599999999999994},{"gamma":1}]},{"featureType":"road.arterial","elementType":"all","stylers":[{"hue":"#FF0300"},{"saturation":-100},{"lightness":51.19999999999999},{"gamma":1}]},{"featureType":"road.local","elementType":"all","stylers":[{"hue":"#FF0300"},{"saturation":-100},{"lightness":52},{"gamma":1}]},{"featureType":"water","elementType":"all","stylers":[{"hue":"#0078FF"},{"saturation":-13.200000000000003},{"lightness":2.4000000000000057},{"gamma":1}]}]
            };
              handler.buildMap({ provider: mapOptions, internal: { id: 'map' } }, function(){
                markers = handler.addMarkers(<%= raw @hash.to_json %>);
              });
            });
          </script>
        <% end %>

app/views/physical_books/_physicalbooks_index_book_card.html.erb
  <% if @physical_books.nil? || @physical_books.empty? %>
    <p>Sorry, we haven't found any results that match your search.</p>
  <% else %>
    <% @physical_books.results.each do |book|%>
      <% if book.is_a? PhysicalBook %>
        <div id ="homepagebooks" class="row">
          <div class="col-md-4">
            <%= link_to(physical_book_path(book), {class: "card-link"}) do %>
            <div class="card">
              <div class="col-xs-4">
                <div class="card-cover">
                  <%= image_tag "#{book.cover_pic_url}", {class: "img-responsive" } %>
                </div>
              </div>
              <div class="col-xs-8">
                <div class="card-category"><%=  book.status %> <%= display_book_price(book) %> </div>
                <div class="card-description">
                  <h2><%= book.title %></h2>
                  <p><%= book.author %></p>
                  <% if current_user %>
                    <% unless current_user.coordinates[0].nil? || book.user == current_user %>
                      <p class="card-km">
                        <%= current_user.distance_from(book.user_coordinates).round(2) %> km away
                      </p>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div>
            <%= link_to(user_path(book.user), {class: "card-link"}) do %>
            <p class="card-user">
              <% avatar_url = book.user.facebook_picture_url || book.user.profile_pic_url  %>
              <%= image_tag avatar_url, {class: "avatar-sm"} %>
            </p>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
        <% elsif book.is_a? User %>
          <div>
            <%= link_to book.first_name + " " + book.last_name, user_path(book.id) %>
          </div>
        <% elsif book.is_a? Genre %>
          <div>
          Click here for more books about <%= link_to book.name, genre_path(book.id) %>
          </div>
        <% end %>
      <% end %>
    <%end %>
</div>

app/views/physical_books/edit.html.erb
<div class="container">
  <h1>Update a book:</h1>
<%= simple_form_for @book do |f| %>
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :description %>
    <%= f.input :status, collection: [ "Keep", "Sell", "Trade"]%>
    <%= f.input :cover_pic_url %>
      <p>Edit the picture of your book</p>
      <%= f.label :picture_url do %>
      <%= f.file_field :picture_url %>
      <%= f.hidden_field :picture_url_cache %>
      <% end %>
    <%= f.input :isbn %>
    <%= f.input :genre_id, collection: Genre.all %>
    <%= f.input :price %>
    <%= f.button :submit, 'Update' %>
  <% end %>
</div>

app/views/physical_books/index.html.erb
<%= content_for(:title) do %>
  Tsundoku | Search
<% end %>

<% form_tag physical_books_path, method: :get do %>
  <p>
    <% text_field_tag :query, params[:query] %>
    <% submit_tag "Search", name: nil %>
  </p>
<% end %>

<!-- card of books -->
<%= render "physicalbooks_index_book_card" %>

app/views/physical_books/new.html.erb
<%= content_for(:title) do %>
  Bookaround | Add a book
<% end %>

  <h2 class="text-center header-form">Add a Book</h2>
  <div class="btn-formo">
    <p>Look for your book here. This will add details automatically.</p>
      <%= form_tag physical_books_searchbook_path, method: :get do %>
        <%= text_field_tag :title_query, params[:title_query], placeholder: "Title, author, etc." %>
        <% end %>
    <hr />
    <p>or fill in the form</p>
  </div>
  <%= simple_form_for @new_physical_book, html: { multipart: :true } do |f| %>
    <%= f.input :title, label: false, placeholder: "Title" %>
    <%= f.input :author, label: false, placeholder: "Author" %>
    <%= f.input :description, label: false, placeholder: "Description", as: :text %>
    <%= f.input :cover_pic_url, label: false, placeholder: "Link to your book's cover" %>
    <%= f.input :isbn, label: false, placeholder: "ISBN" %>
    <%= f.input :genre_id, collection: Genre.all,label: false, prompt: "Genre" %>
    <%= f.input :status, collection: [ "Keep", "Sell", "Trade", "Free"], label: false, prompt: "Status"%>
    <%= f.input :price, label: false, placeholder: "Price" %>
      <%= f.label :picture_url do %>
        <%= f.file_field :picture_url  %>
        <%= f.hidden_field :picture_url_cache %>
        <% end %>

    <div class="btn-center">
      <%= f.button :submit, 'Save', class:  "btn-primary btn-center" %>
    </div>
  <% end %>

app/views/physical_books/retrieve_from_ggb.html.erb
<% @searched_books.each do |searched_book| %>
  <div class="col-md-4">
    <%= link_to(new_physical_book_path(title: searched_book.title, authors: searched_book.authors, isbn: searched_book.isbn, cover_pic_url: searched_book.image_link, description: searched_book.description), {class: "card-link"}) do %>
      <div class="card">
        <div class="col-xs-4">
          <div class="card-cover">
            <% if searched_book.image_link.present? %>
              <%= image_tag searched_book.image_link, {class: "img-responsive" } %>
            <% else %>
              <%= image_tag "http://hdimagesnew.com/wp-content/uploads/2016/09/image-not-found.jpg", {class: "img-responsive" } %>
          <% end %>
          </div>
        </div>
        <div class="col-xs-8">
          <div class="card-description">
            <h2><%= searched_book.title %></h2>
            <p><%= searched_book.authors %></p>
            <p><%= searched_book.isbn  %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/physical_books/show.html.erb
<%= content_for(:title) do %>
  Tsundoku | <%= @book.title %>
<% end %>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-3">
      <%= image_tag "#{@book.cover_pic_url}", {class: "img-responsive" }   %>
      <!-- <a href="#" class="thumbnail" >
        <%#= image_tag "#{@book.picture_url}", {class: "img-responsive" }   %>
      </a> -->
    </div>

    <div class="col-xs-12 col-sm-6 col-md-5">
      <h2><%= @book.title %></h2>
      <h3><%= @book.author %></h3>
      <h3><%= link_to Genre.find(@book.genre_id).name, genre_path(@book.genre_id) %></h3>
      <p class=""><%= @book.description %></p>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-4">
      <% if current_user != @book.user %>
        <%=link_to(user_path(@book.user)) do %>
            <% avatar_url = @book.user.facebook_picture_url || @book.user.profile_pic_url  %>
              <p><%= image_tag avatar_url, class: "avatar-md" %></p>
              <p><%= @book.user.first_name + ' ' + @book.user.last_name %></p>
          <p><%= link_to "Message", new_message_path(to: @book.user, book: @book, recipient: @book.user), {class: "btn-medium"} %></p>
        <% end %>
        <% unless !current_user %>
          <% current_wishlist_item = current_user.contains_book?(@book.id) %>
          <% if current_wishlist_item.nil? %>
            <div class="saved"><%= link_to "Save to wishlist", wishlist_items_path(physical_book_id: @book.id, wishlist_id: current_user.wishlist.id), method: "create" %>
            </div>
          <% else %>
            <div class="removed"><%= link_to "Remove from wishlist", wishlist_item_path(current_wishlist_item.id), method: "delete", class: "" %>
            </div>
          <% end %>
        <% end %>
        <%= render "google_maps" %>
      <% end %>

      <% if current_user == @book.user %>
          <p><%= link_to "Update book details", edit_physical_book_path(@book), {class: ""} %></p>
          <p>
            <%= link_to "Delete book", physical_book_path(@book), class: "", method: :delete, data: {confirm: "Are you sure you want to delete this book?"} %>
            <% end %>
          </p>


    </div>
  </div>