config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :views

  root 'static_pages#home'

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply, :restore, :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  resources :genres, only: [:show]
  get 'physical_books/searchbook' => 'physical_books#retrieve_from_ggb'
  resources 'physical_books'
  resources 'users', only: [:index, :show]
  get 'users/:id/index_of_books' => 'users#index_of_books', as: :index_of_books


  resource :wishlist, only: [:show]
  resources :wishlist_items, only: [:create, :destroy]

  get "static_pages/about", :as => 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]


  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
      @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    @other = @conversation.participants.map do  |man|
      man if man != current_user
    end
    @other = @other.compact
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  private

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

   def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
    <%= link_to 'Restore', restore_conversation_path(conversation), class: '', method: :post %>
    <% else %>
    <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>
'.html_safe, conversation_path(conversation), class: '', method: :delete,
    data: {confirm: 'Are you sure?'} %>

      <% if conversation.is_unread?(current_user) %>
      <%= link_to '<i class="fa fa-check-square-o" aria-hidden="true"></i>
'.html_safe, mark_as_read_conversation_path(conversation),
      class: '', method: :post %>
      <% end %>
    <% end %>
  </div>
</li>

app/views/conversations/index.html.erb
<%= content_for(:title) do %>
  Bookaround | Messages
<% end %>

  <h2 class="text-center">Messages</h2>

  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">
        <%= mailbox_section 'inbox', @box %>
        <%= mailbox_section 'sent', @box %>
        <%= mailbox_section 'trash', @box %>
        <li><%= link_to 'New chat', new_message_path %></li>
      </ul>
    </div>

    <div class="col-sm-9">
      <% if @box == 'trash' %>
      <br>
      <%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-primary btn-formo', method: :delete,
       data: {confirm: 'Are you sure?'} %>
       <% end %>

       <ul class="list-group">
        <%= render partial: 'conversations/conversation', collection: @conversations %>
      </ul>

      <%= will_paginate %>
    </div>
  </div>

app/views/conversations/show.html.erb
<%= content_for(:title) do %>
  Bookaround | Messages
<% end %>

  <div class="msg-avatar-left">
    <%= link_to(user_path(@other[0]), {class: "card-link"}) do %>
      <%= image_tag @other[0].profile_pic_url, class: "avatar-md" %>
        <%= @other[0].first_name %>
      <% end %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading"><%= @conversation.subject %></div>
    <div class="panel-body msg-background">
      <div class="row">
        <div class="col-xs-12">
          <div class="messages">
              <% @conversation.receipts_for(current_user).reverse.each do |receipt| %>
              <% message = receipt.message %>

              <% avatar_url = message.sender.facebook_picture_url || message.sender.profile_pic_url %>

          <% if message.sender.first_name == current_user.first_name %>
            <div class="msg-cont-sender">
                <div class="msg-sender">
                  <%#= image_tag avatar_url, class: "avatar-sm" %>
                    <%#= message.sender.first_name %>
                    <div class="msg-content">
                      <p><%= message.body %></p>
                    </div>
                    <div class="msg-date">
                      <%= message.created_at.strftime("%H:%M") %>
                      </div>
                    </div>
                </div>
              <% else %>
              <div class="msg-cont-receiver">
                  <div class="msg-receiver">
                  <%#= image_tag avatar_url, class: "avatar-sm" %>
                    <%#= message.sender.first_name %>
                    <div class="msg-content">
                      <p><%= message.body %></p>
                    </div>
                    <div class="msg-date">
                      <%= message.created_at.strftime("%H:%M") %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

        <%= form_tag reply_conversation_path(@conversation), method: :post do %>
          <div class="form-group">
            <%= text_field_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
          </div>
        <% end %>
    </div>
  </div>