config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :views

  root 'static_pages#home'

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply, :restore, :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  resources :genres, only: [:show]
  get 'physical_books/searchbook' => 'physical_books#retrieve_from_ggb'
  resources 'physical_books'
  resources 'users', only: [:index, :show]
  get 'users/:id/index_of_books' => 'users#index_of_books', as: :index_of_books


  resource :wishlist, only: [:show]
  resources :wishlist_items, only: [:create, :destroy]

  get "static_pages/about", :as => 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  acts_as_messageable
  # association for wishlist item
  # association with physical books
  has_many :physical_books, dependent: :destroy
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id"
  has_many :sold_transactions, class_name: "Transaction", foreign_key: "seller_id"
  has_many :received_transactions, class_name: "Transaction", foreign_key: "receiver_id"
  has_one :wishlist
  has_many :wishlist_items, through: :wishlist # doublecheck with Martin


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  # validates_presence_of :profile_pic_url
  # validates_integrity_of :profile_pic_url
  # validates_processing_of :profile_pic_url

  # validates :street1, presence: true
  # validates :postcode, presence: true
  # validates :city, presence: true
  # validates :country, presence: true

  #Facebook Log In
  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  # Uploader of pictures
  mount_uploader :profile_pic_url, AvatarUploader

  #retrieves last book from given user
  def last_book
    physical_books.last
  end

  def contains_book? book_id
    self.wishlist_items.where(:physical_book_id => book_id).first
  end

  def coordinates
    [latitude, longitude]
  end

  def address
    [street1, street2, postcode, city, country].compact.join(', ')
  end
  geocoded_by :address # concatenation of variables: "street1", "street2", "postcode", "city", "country"

  after_validation :geocode, if: :address_changed?

  def address_changed?
    if street1_changed? || street2_changed? || postcode_changed? || city_changed? || country_changed?
      return true
    else
      return false
    end
  end

  searchkick

  #wishlist of user
  after_create :create_wishlist

  private

  def create_wishlist
    @new_wishlist = Wishlist.create(user: self)
    User.reindex
  end
end

# Mailboxer email configuration
def mailboxer_email(object)
  email
end

# Mailboxer users page
def index
    @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    # @result = request.location #CHECK WITH THOMAS
    @users = User.where.not(latitude: nil, longitude: nil) #comes from the LeWagon template on web
    # @users_coordinates = []  #adapted from Karr
    # @users.each do |user|    #adapted from Karr
    #   user_coordinates = { lat: user.latitude, lng: user.longitude } #adapted from Karr
    #   @users_coordinates << user_coordinates    #adapted from Karr
    # end
  end

  def index_of_books
    @books = @user.physical_books
  end


  def show
    @books = @user.physical_books
    @last_book = @user.last_book
    @user_coordinates = { lat: @user.latitude, lng: @user.longitude }
    @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users_book_card.html.erb
<% @books.each_slice(6) do |books| %>
  <div id ="homepagebooks" class="row">
    <% books.each do |book| %>
      <div class="col-md-4">
        <%= link_to(physical_book_path(book), {class: "card-link"}) do %>
        <div class="card">
          <div class="col-xs-4">
            <div class="card-cover">
              <%= image_tag "#{book.cover_pic_url}", {class: "img-responsive" } %>
            </div>
          </div>
          <div class="col-xs-8">
            <div class="card-category"><%=  book.status %> <%= display_book_price(book) %> </div>
            <div class="card-description">
              <h2><%= book.title %></h2>
              <p><%= book.author %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= will_paginate %>
<ul>
  <% @users.each do |user| %>
    <li>
      <strong><%= user.first_name %></strong>
      <% unless current_user == user %>
        <%= link_to 'Send message', new_message_path(to: user.id), class: 'btn btn-default btn-sm' %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/show.html.erb
<%= content_for(:title) do %>
  Tsundoku | <%= @user.first_name + ' ' + @user.last_name %>
<% end %>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-3">
    <div>
      <% avatar_url = @user.facebook_picture_url || @user.profile_pic_url || "http://placehold.it/30x30" %>
      <%= image_tag avatar_url, {class: "avatar-profile-square"} %>
    </div>
    <h2><%= @user.first_name %><%= " " %><%= @user.last_name %></h2>
    <div>
      <% if !@user.city %>
        <%= link_to "Add your address", edit_user_registration_path %>
      <% else %>
        <p><%= @user.city %> · <%= @user.country %></p>
      <% end %>
    </div>
    <div>
      <% if !@user.bio %>
        <%= link_to "Say something about you", edit_user_registration_path %>
      <% else %>
        <p><%= @user.bio %></p>
      <% end %>
    </div>
    <% if current_user == User.find(params[:id]) %>
      <p><%= link_to "Add a book", new_physical_book_path, class: "" %></p>
      <p><%= link_to "Edit profile", edit_user_registration_path, class: "" %></p>
    <% else %>
      <p><%= link_to "Message", new_message_path(to: @user), class: "" %></p>
      <%#= link_to "See all books", index_of_books_path(@user), class: "" %>
    <% end %>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-9">
    <%= render "users_book_card" %>
  </div>
</div>