config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_for :views

  root 'static_pages#home'

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply, :restore, :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  resources :genres, only: [:show]
  get 'physical_books/searchbook' => 'physical_books#retrieve_from_ggb'
  resources 'physical_books'
  resources 'users', only: [:index, :show]
  get 'users/:id/index_of_books' => 'users#index_of_books', as: :index_of_books


  resource :wishlist, only: [:show]
  resources :wishlist_items, only: [:create, :destroy]

  get "static_pages/about", :as => 'about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<!-- <div class="banner" style="background-image: url(<%=  image_path "main_image.jpg" %>);">
 --><div class="banner">
  <div class="banner-content">
    <p>Find, sell and exchange the books you love in your neighbourhood.</p>
    <div class="number of users">
      <!-- <p id="banner-bottom">Find out how it works</p> -->
       <%#=  count_users_in_area(brussels_coordinates) %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer container">

  <!-- Desktop footer -->
    <div class="footer-container footer-right">
     <%= link_to 'About', about_path, class: 'navbar-wagon-link' %>
    <!-- <a href="./static_pages/about">
      <div class="footer-item">About us</div>
    </a> -->
    <a href="mailto:samuelyret@gmail.com">
      <div class="footer-item navbar-wagon-link">Contact</div>
    </a>
    <!-- <div class="footer-item">Terms &amp Privacy</div> -->
    <div class="footer-item">
   <!--    <a href="https://www.facebook.com/atsundoku/?ref=bookmarks" target="_blank">
        <i class="fa fa-facebook-official navbar-wagon-link" aria-hidden="true"></i>
      </a>
    </div>
    <div class="footer-item">
      <a href="https://twitter.com/atsundoku" target="_blank">
        <i class="fa fa-twitter navbar-wagon-link" aria-hidden="true"></i>
      </a> -->
    </div>
  </div>


  <!-- Mobile footer -->
   <!--  <div class="footer-container footer-right hidden-md hidden-lg">
     <%#= link_to 'About', about_path %>
    <a href="mailto:samuelyret@gmail.com">
      <i class="fa fa-envelope"></i>
    </a> -->
    <!-- <div class="footer-item">Terms &amp Privacy</div> -->
      <!-- <a href="https://www.facebook.com/atsundoku/?ref=bookmarks" target="_blank">
        <i class="fa fa-facebook-official" aria-hidden="true"></i>
      </a>
      <a href="https://twitter.com/atsundoku" target="_blank">
        <i class="fa fa-twitter" aria-hidden="true"></i>
      </a> -->
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1 class="logo">Tsundoku</h1>
  <% end %>

  <!-- Desktop navbar -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
  <form action="/physical_books" method="get" name="query" class="navbar-wagon-search">
    <input type="text" name="query" class="navbar-wagon-search-input" placeholder="Search books" onkeyup="buttonUp();" required>
    <button type="submit" class="navbar-wagon-search-btn">
    </button>
  </form>

    <% if user_signed_in? %>
    <%= link_to "Add book", new_physical_book_path(@physical_books), class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Wishlist', wishlist_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Notification link-->
      <div class="badge-container">
          <%= link_to 'Messages', conversations_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <div class="badge"></div>
      </div>

    <!-- Profile picture and dropdown -->
    <% avatar_url = current_user.facebook_picture_url || current_user.profile_pic_url || "http://placehold.it/30x30" %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag avatar_url, class: "avatar-sm dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
              <%= link_to user_path(current_user) do %>
              <%= t(".profile", default: "My profile") %>
            <% end %>
          </li>
          <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
          </li>
        </ul>
      </div>
    </div>


    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Log In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>


  <!-- Mobile navbar -->
  <div class="navbar-wagon-item hidden-md hidden-lg">

    <form action="/physical_books" method="get" name="query" class="navbar-wagon-search">
    <input type="text" name="query" class="navbar-wagon-search-input" placeholder="Search books" onkeyup="buttonUp();" required>
    <button type="submit" class="navbar-wagon-search-btn">
    </button>
  </form>

    <!-- If logged in mobile -->
    <% if user_signed_in? %>

      <!-- Mobile dropdown menu -->
      <div id="myNav" class="overlay">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <div class="overlay-content">
        <a href="#">
          <%= link_to user_path(current_user) do %>
            <% avatar_url = current_user.facebook_picture_url || current_user.profile_pic_url %>
            <%= image_tag avatar_url, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
        </a>
        <div class="menu-items">
          <a href="#">
            <%= link_to user_path(current_user) do %>
              <%= t(".profile", default: "My profile") %>
            <% end %>
          </a>
          <a href="#">
             <%= link_to 'Messages', conversations_path %>
          </a>
          <a href="#">
            <%= link_to wishlist_path do %>
              <%= t(".profile", default: "My Wishlist") %>
            <% end %>
          </a>
          <a href="#">
            <%= link_to new_physical_book_path(@physical_books) do %>
              <%= t(".profile", default: "Add book") %>
            <% end %>
          </a>
          <a href="#">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </a>
        </div>
      </div>
    </div>

    <div class="menu-btn">
      <span style="cursor:pointer" onclick="openNav()">
        <i class="fa fa-bars menu-bars" aria-hidden="true"></i>
      </span>
    </div>

    <!-- if not logged in mobile -->
    <% else %>
      <%= link_to(new_user_session_path) do %>
        <i class="fa fa-bars menu-bars" aria-hidden="true"></i>
      <% end %>
    <% end %>
  </div>
</div>